[[constraint]]
  name = "github.com/asdine/storm"
  version = "~2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/go-flags"

[[constraint]]
  branch = "master"
  name = "github.com/chappjc/logrus-prefix"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/EXCCoin/exccd"

[[constraint]]
  branch = "master"
  name = "github.com/EXCCoin/exccwallet"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  branch = "master"
  name = "github.com/googollee/go-socket.io"

[[constraint]]
  name = "github.com/go-chi/docgen"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/jrick/logrotate"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.0"

[[constraint]]
  name = "github.com/oleiade/lane"
  version = "1.0.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/shiena/ansicolor"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btclog"

[prune]
  go-tests = true
  unused-packages = true
