name: Build and Test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build-go:
    name: Go Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Install Linters
      run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2
    - name: Go Build exccdata
      run: go build -v ./...
      working-directory: ./cmd/exccdata
    - name: Go Tests
      run: ./run_tests.sh

  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: cmd/exccdata/package-lock.json

      - name: npm clean-install
        run: npm clean-install
        working-directory: ./cmd/exccdata

      - name: npm run build
        run: |
          npm run build
          git diff --exit-code views/extras.tmpl
        working-directory: ./cmd/exccdata
